services:
    php:
        container_name: php
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./todolist:/var/www/html/
        ports:
            - 8000:80
            
    db:
        container_name: db
        image: mysql
        restart: always
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: todolist
            MYSQL_USER: mysql
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"